// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canvas.sql

package sqlc

import (
	"context"
)

const checkCanvasAccess = `-- name: CheckCanvasAccess :one
SELECT EXISTS (
    SELECT 1 FROM "Canvas" 
    WHERE "Canvas".id = $1 
    AND (
        "Canvas"."userId" = $2 
        OR visibility = 'PUBLIC'
        OR EXISTS (
            SELECT 1 FROM "CanvasShare" 
            WHERE "CanvasShare"."canvasId" = "Canvas".id 
            AND "CanvasShare"."userId" = $2
        )
    )
)
`

type CheckCanvasAccessParams struct {
	ID     string `json:"id"`
	UserId string `json:"userId"`
}

func (q *Queries) CheckCanvasAccess(ctx context.Context, arg CheckCanvasAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCanvasAccess, arg.ID, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
