// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	UserId            string           `json:"userId"`
	Type              string           `json:"type"`
	Provider          string           `json:"provider"`
	ProviderAccountId string           `json:"providerAccountId"`
	RefreshToken      pgtype.Text      `json:"refresh_token"`
	AccessToken       pgtype.Text      `json:"access_token"`
	ExpiresAt         pgtype.Int4      `json:"expires_at"`
	TokenType         pgtype.Text      `json:"token_type"`
	Scope             pgtype.Text      `json:"scope"`
	IDToken           pgtype.Text      `json:"id_token"`
	SessionState      pgtype.Text      `json:"session_state"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
}

type Canva struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	UserId    string           `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type Session struct {
	SessionToken string           `json:"sessionToken"`
	UserId       string           `json:"userId"`
	Expires      pgtype.Timestamp `json:"expires"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type Shape struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	X         float64          `json:"x"`
	Y         float64          `json:"y"`
	Width     float64          `json:"width"`
	Height    float64          `json:"height"`
	Color     string           `json:"color"`
	ZIndex    int32            `json:"zIndex"`
	CanvasId  string           `json:"canvasId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID            string           `json:"id"`
	Name          pgtype.Text      `json:"name"`
	Email         string           `json:"email"`
	EmailVerified pgtype.Timestamp `json:"emailVerified"`
	Image         pgtype.Text      `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
}

type VerificationToken struct {
	Identifier string           `json:"identifier"`
	Token      string           `json:"token"`
	Expires    pgtype.Timestamp `json:"expires"`
}
