// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CheckCanvasAccess(ctx context.Context, arg CheckCanvasAccessParams) (bool, error)
	DeleteShape(ctx context.Context, arg DeleteShapeParams) error
	GetShape(ctx context.Context, id string) (GetShapeRow, error)
	GetShapesByCanvasId(ctx context.Context, canvasid string) ([]GetShapesByCanvasIdRow, error)
	UpsertShape(ctx context.Context, arg UpsertShapeParams) error
}

var _ Querier = (*Queries)(nil)
