// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shapes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteShape = `-- name: DeleteShape :exec
DELETE FROM "Shape" WHERE id = $1 AND "canvasId" = $2
`

type DeleteShapeParams struct {
	ID       string `json:"id"`
	CanvasId string `json:"canvasId"`
}

func (q *Queries) DeleteShape(ctx context.Context, arg DeleteShapeParams) error {
	_, err := q.db.Exec(ctx, deleteShape, arg.ID, arg.CanvasId)
	return err
}

const getShape = `-- name: GetShape :one
SELECT id, type, x, y, width, height, color, "zIndex", "canvasId", "updatedAt"
FROM "Shape"
WHERE id = $1
`

type GetShapeRow struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	X         float64          `json:"x"`
	Y         float64          `json:"y"`
	Width     float64          `json:"width"`
	Height    float64          `json:"height"`
	Color     string           `json:"color"`
	ZIndex    int32            `json:"zIndex"`
	CanvasId  string           `json:"canvasId"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetShape(ctx context.Context, id string) (GetShapeRow, error) {
	row := q.db.QueryRow(ctx, getShape, id)
	var i GetShapeRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Color,
		&i.ZIndex,
		&i.CanvasId,
		&i.UpdatedAt,
	)
	return i, err
}

const getShapesByCanvasId = `-- name: GetShapesByCanvasId :many
SELECT id, type, x, y, width, height, color, "zIndex", "canvasId", "updatedAt"
FROM "Shape"
WHERE "canvasId" = $1
`

type GetShapesByCanvasIdRow struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	X         float64          `json:"x"`
	Y         float64          `json:"y"`
	Width     float64          `json:"width"`
	Height    float64          `json:"height"`
	Color     string           `json:"color"`
	ZIndex    int32            `json:"zIndex"`
	CanvasId  string           `json:"canvasId"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetShapesByCanvasId(ctx context.Context, canvasid string) ([]GetShapesByCanvasIdRow, error) {
	rows, err := q.db.Query(ctx, getShapesByCanvasId, canvasid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShapesByCanvasIdRow
	for rows.Next() {
		var i GetShapesByCanvasIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Color,
			&i.ZIndex,
			&i.CanvasId,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShape = `-- name: UpsertShape :exec
INSERT INTO "Shape" (id, type, x, y, width, height, color, "zIndex", "canvasId", "updatedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (id) DO UPDATE 
SET type = EXCLUDED.type,
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    color = EXCLUDED.color,
    "zIndex" = EXCLUDED."zIndex",
    "canvasId" = EXCLUDED."canvasId",
    "updatedAt" = NOW()
`

type UpsertShapeParams struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Width    float64 `json:"width"`
	Height   float64 `json:"height"`
	Color    string  `json:"color"`
	ZIndex   int32   `json:"zIndex"`
	CanvasId string  `json:"canvasId"`
}

func (q *Queries) UpsertShape(ctx context.Context, arg UpsertShapeParams) error {
	_, err := q.db.Exec(ctx, upsertShape,
		arg.ID,
		arg.Type,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Color,
		arg.ZIndex,
		arg.CanvasId,
	)
	return err
}
